services:
  cube:
    build: . 
    image: cubejs/cube:latest
    ports:
      - "4000:4000"
    environment:
      - CUBEJS_DB_TYPE=duckdb
      - CUBEJS_DB_DUCKDB_DATABASE_PATH=/data/warehouse.duckdb
      - DEVSERVER=true
      - CUBEJS_GRAPHQL=true
    volumes:
      - .:/cube/conf
      - ../data/duckdb:/data